services:

  test:
    image: ${DOCKERHUB_USERNAME}/crm-backend:${TAG}
    command: bash -c "pytest --maxfail=3 --disable-warnings || exit 1"
    networks:
      - crm_network
    volumes:
      - .:/app
      - ./tests:/app/tests
    environment:
      - PYTHONPATH=/app

  web:
    image: ${DOCKERHUB_USERNAME}/crm-backend:${TAG}
    tty: true
    stdin_open: true
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    command: >
       gunicorn -c gunicorn.conf.py run:app
    networks:
      - crm_network

networks:
  crm_network:
    external: true
