services:
  web:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "${PORT}:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs  
    command: >
       gunicorn -c gunicorn.conf.py run:app
    networks:
      - crm_network

networks:
  crm_network:
    external: true
