services:

  web:
    image: ${DOCKERHUB_USERNAME}/crm-backend:${TAG}
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "${PORT}:8000"
    volumes:
      - ./logs:/app/logs  
      - .env:/app/.env 
    command: >
       gunicorn -c gunicorn.conf.py run:app
    networks:
      - crm_network

  template-service:
    image: ${DOCKERHUB_USERNAME}/template-service:latest
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs  
      - .env:/app/.env 
    networks:
      - crm_network

networks:
  crm_network:
    external: true
