services:
  web:
    #image: ${DOCKERHUB_USERNAME}/crm-backend:${TAG}
    build: .
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "${PORT}:8000"
    volumes:
      - ./logs:/app/logs  
      - .env:/app/.env 
    command: >
       gunicorn -c gunicorn.conf.py run:app
    networks:
      - crm_network

networks:
  crm_network:
    external: true
