services:
  redis:
      image: redis:7-alpine
      container_name: redis
      ports:
        - "6379:6379"
      restart: always
      networks:
      - crm_network

  web:
    image: ${DOCKERHUB_USERNAME}/crm-backend:${TAG}
    container_name: crm-backend${CONFIG_NAME}
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "${PORT}:8000"
    volumes:
      - ./logs:/app/logs  
      - .env:/app/.env 
    command: >
       gunicorn -c gunicorn.conf.py run:app
    networks:
      - crm_network

  template-service:
    image: ${DOCKERHUB_USERNAME}/template-service:latest
    container_name: template-service
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs  
      - .env:/app/.env 
    networks:
      - crm_network

networks:
  crm_network:
    external: true
