name: Deploy to Server

on:
  push:
    branches: [master, dev]

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Determine Deployment Path
        run: |
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            echo "DEPLOY_PATH=apps/crm-backend" >> $GITHUB_ENV
            echo "GIT_BRANCH=master" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "DEPLOY_PATH=apps/crm-backend-dev" >> $GITHUB_ENV
            echo "GIT_BRANCH=dev" >> $GITHUB_ENV
          else
            echo "❌ Неизвестная ветка! Прерываем процесс."
            exit 1
          fi


      - name: Pull Latest Code and Run Tests
        id: test
        run: |
          echo "🚀 Обновляем код и запускаем тесты в $DEPLOY_PATH..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            cd $DEPLOY_PATH &&
            git pull origin $GIT_BRANCH &&
            TEST_MODE=1 docker compose build test &&
            docker compose up test
          "
        continue-on-error: true



      - name: Clean up Docker Cache
        if: always()  # Очистка запускается в любом случае (успех или неудача тестов)
        run: |
          echo "🧹 Очищаем кеш и неиспользуемые Docker-ресурсы..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            docker system prune -af &&
            docker volume prune -f
          "

      - name: Rollback on Failure
        if: steps.test.outcome == 'failure'
        run: |
          echo "🚨 Тесты провалились! Откатываемся на предыдущую рабочую версию..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            cd $DEPLOY_PATH &&
            git fetch origin &&
            git checkout $(git rev-list --max-count=1 HEAD --skip=1 || echo 'HEAD')
          "
          exit 1


      - name: Save Logs on Failure
        if: steps.test.outcome == 'failure'
        run: |
          echo "💾 Сохраняем логи тестов..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            cd $DEPLOY_PATH &&
            docker compose logs > failed_tests.log
          "


      - name: Deploy Application
        if: success()
        run: |
          echo "🚀 Тесты успешны, деплоим..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            cd $DEPLOY_PATH &&
            docker compose down &&
            docker compose up --build -d
          "
